### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by daimor** [zrml/ccontainermain#2]
Sometime I see that running container can't finish.

```
daimor@daimor-pc:~$ docker run -it zrml/intersystems-cachedb:2016.2.0.619.0 -shmem=1024
2016/03/19 14:02:07 Starting Caché...
```

and I can't stop or kill such container, only reboot may help in this case

**Comment by zrml** [comment]
the flag you specified is not valid. We should trap it better if we don't...

**Comment by zrml** [comment]
@daimor, I'm not sure why I said the above when it is a valid option. Apologies.
If you run on a kernel per 3.16, then you need to tune the kernel shmmax and related so that you can access more mem. Your container does not have a kernel so it tries to tune the host system for which you have no access from the container. Therefore, your only solution is to use "--privileged" which of course is a dangerous option.

My advice is to use & run >3.16 kernel. Use Ubuntu 15.10 and above for example. You can still run CentOS, RH and SUSE as a container for Caché.

## HTH
